apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: splitwise-gateway
  namespace: splitwise
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: splitwise-tls-cert
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: splitwise-route
  namespace: splitwise
spec:
  parentRefs:
    - name: splitwise-gateway
      namespace: splitwise
  hostnames:
    - "splitewise.devopshome.online"
  rules:
    # Route API endpoints and uploaded files to the backend Service
    - matches:
        - path:
            type: PathPrefix
            value: /api
        - path:
            type: PathPrefix
            value: /uploads
      backendRefs:
        - name: splitwise-backend
          port: 5000
    # Route all other traffic to the frontend Service
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: splitwise-frontend
          port: 80
