apiVersion: v1
kind: Secret
metadata:
  name: splitwise-secrets
  namespace: splitwise
type: Opaque
stringData:
  DB_HOST: "140.245.237.157"
  DB_PORT: "3306"
  DB_USER: "splitwise_user"
  DB_PASSWORD: "Ajaykumar@12."
  DB_NAME: "splitwise"
  JWT_SECRET: "splitwise_jwt_secret_dev_key_987654321"
  JWT_EXPIRE: "7d"
  NODE_ENV: "production"
